### ISSUE TITLE
数据集data.zip无法解压

### ISSUE THREAD

**Issue by peterz3g** [issaccv/aiops24-RAG-demo#1]
# unzip demo/dataset/data.zip -d demo/
Archive:  demo/dataset/data.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of demo/dataset/data.zip or
        demo/dataset/data.zip.zip, and cannot find demo/dataset/data.zip.ZIP, period.

**Comment by issaccv** [comment]
请按照bug模板要求填写复现所需要的步骤，另外请留意执行run.sh 的所在路径

**Comment by zhudongwork** [comment]
> # unzip demo/dataset/data.zip -d demo/
> Archive: demo/dataset/data.zip End-of-central-directory signature not found. Either this file is not a zipfile, or it constitutes one disk of a multi-part archive. In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive. unzip: cannot find zipfile directory in one of demo/dataset/data.zip or demo/dataset/data.zip.zip, and cannot find demo/dataset/data.zip.ZIP, period.

一样的问题。应该是网络问题导致zip数据下载不全，把下载的dataset全删了然后重新下载，多试几次
