### ISSUE TITLE
[BUG]运行main.py的时候 huggingface无法运行

### ISSUE THREAD

**Issue by BarryYin** [issaccv/aiops24-RAG-demo#12]
### 检查之前的issues

- [X] 我已经检查过之前的issues，没有我遇到的问题

### 描述Bug

![image](https://github.com/issaccv/aiops24-RAG-demo/assets/30064067/3e8afd94-5366-4a67-8ba7-3bfa27399419)
运行shi时一直卡在这里，无法继续运行

### 复现步骤

mac, glm分支，安装完所有依赖，运行main.py出现问题

### 代码分支

glm

### 运行环境

本地环境

**Comment by issaccv** [comment]
generating embedding这一步的进度条确实会卡住，但是可以检查mac的CPU/GPU占用来确定Embedding是否在真的进行。我们建议还是使用带有CUDA的环境进行Demo的复现。Pytorch在MPS上的很多op都是未实现的状态。

以下信息供你参考：
使用NVIDIA A10 GPU进行Embedding生成大约需要 1 分钟
