### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by buycarr** [issaccv/aiops24-RAG-demo#13]
### 检查之前的issues

- [X] 我已经检查过之前的issues，没有我遇到的问题

### 描述Bug

1.运行main的时候 在这步卡好久好久：
Generating embeddings:   0%|          | 0/246 [00:00<?, ?it/s]
2.在from custom.template import SUMMARY_EXTRACT_TEMPLATE的时候 from custom的时候 显示没有custom 也就是没法使用from custom

### 复现步骤

正常按照官网的流程走下来就这样
1.创建虚拟环境

conda create -n rag_demo python==3.11

2.启动虚拟环境

conda activate rag_demo

3.克隆demo

git clone https://github.com/issaccv/aiops24-RAG-demo

4.完成demo环境的初始化

①找到aiops24-RAG-demo所在文件夹，点进去，鼠标右键打开Open Git Bash here
②git checkout glm 
④bash run.sh
⑤.打开虚拟环境，进入到aiops24-RAG-demo下，然后执行：

pip install -r demo/requirements.txt（执行时间比较久）

### 代码分支

glm

### 运行环境

本地环境

**Comment by issaccv** [comment]
1. dupe #12
2. 请检查执行代码时所在的目录

**Comment by buycarr** [comment]
copy that!  thank you



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月18日 22:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [issaccv/aiops24-RAG-demo] [BUG] (Issue #13) |

Closed #13 as completed.
