### ISSUE TITLE
[BUG] 每次执行main都要重新分块、嵌入，时间比较久怎么办

### ISSUE THREAD

**Issue by jiaohuix** [issaccv/aiops24-RAG-demo#15]
### 检查之前的issues

- [X] 我已经检查过之前的issues（包括已经关闭的issue），没有我遇到的问题

### 描述Bug

readme说“第一次运行会进行文档的切块和嵌入，时间较久，后续过程如果需要重新嵌入”。
实际上每次都需要重新嵌入，如何把qdrant的嵌入持久化到本地？

### 复现步骤

python main.py

### 预期行为

向量数据库
持久到本地

### 代码分支

main

### 运行环境

本地环境

**Comment by KunChiang** [comment]
docker本地起一个Qdrant

**Comment by jiaohuix** [comment]
@KunChiang  您好，我用qdrant云端的数据库，从0.63掉到0.61正常嘛

**Comment by issaccv** [comment]
最终评分和qdrant是否在云端无关，评分有一定的随机性，可以多提交几次看看

**Comment by jiaohuix** [comment]
@issaccv ok，谢谢大佬
