### ISSUE TITLE
utf-8' codec can't encode characters in position 73-80: surrogates

### ISSUE THREAD

**Issue by wangyongbing** [issaccv/aiops24-RAG-demo#3]
await pipeline.arun(documents=data, show_progress=True, num_workers=1)
报错 

File "/chatolm/my project/aiops24-RAG-demo-gim/main,py", line s1, in main

await pipeline,arun(documentsedata, show progress-True, num workers 1)

File "/root/miniconda3/lib/python3,10/site-packages/llama index/core/ingestion/pipelin
return sha256l[nodes str + t ransform string) ,encode( "utf-8")).herdinest()

UnicodeEncodeError: utf-8' codec can't encode characters in position 73-80: surrogates

**Comment by issaccv** [comment]
https://stackoverflow.com/questions/27366479/python-3-os-walk-file-paths-unicodeencodeerror-utf-8-codec-cant-encode-s

请检查你本地环境的中文编码是否正确
