### ISSUE TITLE
[BUG]TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'NoneType'

### ISSUE THREAD

**Issue by zhudongwork** [issaccv/aiops24-RAG-demo#6]
### 检查之前的issues

- [X] 我已经检查过之前的issues，没有我遇到的问题

### 描述Bug

运行python main.py报错

Traceback (most recent call last):
  File "/home/aiops24-RAG-demo/demo/main.py", line 12, in <module>
    from pipeline.rag import QdrantRetriever, generation_with_knowledge_retrieval
  File "/home/aiops24-RAG-demo/demo/pipeline/rag.py", line 64, in <module>
    reranker: BaseNodePostprocessor | None = None,
TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'NoneType'

### 复现步骤

python main.py

### 代码分支

glm

### 运行环境

本地环境

**Comment by issaccv** [comment]
本地Python版本过低，推荐3.10及以上
