### ISSUE TITLE
[BUG]httpx.HTTPStatusError

### ISSUE THREAD

**Issue by accqaz** [issaccv/aiops24-RAG-demo#8]
### 检查之前的issues

- [X] 我已经检查过之前的issues，没有我遇到的问题

### 描述Bug

本地环境运行demo，出现“    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '502 Bad Gateway' for url 'http://localhost:11434/api/generate'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502  ”要怎么排查问题？

### 复现步骤

运行demo

### 代码分支

main

### 运行环境

本地环境

**Comment by issaccv** [comment]
和 #7  重复

**Comment by accqaz** [comment]
> 和 #7 重复

请问具体要怎么解决呢？http://localhost:11434网址显示的是ollama is running，是因为windows操作系统的原因嘛？

**Comment by issaccv** [comment]
我们没有在windows下测试过ollama，ollama在Windows的发行状态也是alpha，如果有条件可以在WSL中进行demo复现
